//! The stdlib stub registration table mapping OTP `module:function/arity`
//! names to native BIF implementations.

use crate::atom::{Atom, AtomTable};
use crate::native::{BifRegistryImpl, Capability, NativeFn, NativeRegistrationError};
use crate::scheduler::dirty::DirtySchedulerKind;

use super::misc_bifs::{
    bif_binary_part, bif_characters_to_binary, bif_characters_to_list, bif_debug_options,
    bif_fun_info, bif_fwrite_g, bif_identity, bif_init_stop, bif_logger_warning,
    bif_rand_uniform,
};
use super::bitwise_bifs::{bif_band, bif_bnot, bif_bor, bif_bsl, bif_bsr, bif_bxor};
use super::collection_bifs::{
    bif_lists_reverse, bif_maps_from_list, bif_maps_map, bif_maps_merge, bif_maps_remove,
    bif_timer_sleep,
};
use super::encoding_bifs::{
    bif_base64_decode, bif_base64_encode, bif_binary_decode_hex, bif_binary_encode_hex,
};
use super::gleam_stdlib_ffi::{
    bif_contains_string, bif_crop_string, bif_inspect, bif_iodata_append, bif_less_than, bif_slice,
    bif_string_ends_with, bif_string_pop_grapheme, bif_string_remove_prefix,
    bif_string_remove_suffix, bif_string_replace, bif_string_starts_with,
    bif_utf_codepoint_list_to_string,
};
use super::gleam_stdlib_ffi2::{
    bif_base16_decode as bif_gleam_base16_decode, bif_base16_encode as bif_gleam_base16_encode,
    bif_base64_decode as bif_gleam_base64_decode, bif_base64_encode as bif_gleam_base64_encode,
    bif_bit_array as bif_gleam_bit_array, bif_bit_array_concat as bif_gleam_bit_array_concat,
    bif_bit_array_pad_to_bytes as bif_gleam_bit_array_pad_to_bytes,
    bif_bit_array_slice as bif_gleam_bit_array_slice,
    bif_bit_array_to_int_and_size as bif_gleam_bit_array_to_int_and_size, bif_classify_dynamic,
    bif_dict, bif_float as bif_gleam_float, bif_float_to_string, bif_index, bif_int,
    bif_int_from_base_string, bif_is_null, bif_list as bif_gleam_list, bif_map_get,
    bif_parse_float, bif_parse_int, bif_print, bif_print_error, bif_println, bif_println_error,
    bif_wrap_list,
};
use super::io_bifs::{
    bif_io_format_2, bif_io_format_3, bif_io_get_line_1, bif_io_lib_format_2, bif_io_put_chars_1,
    bif_io_put_chars_2, bif_io_setopts_2,
};
use super::lists_bifs::{
    bif_lists_append_1, bif_lists_append_2, bif_lists_flatten, bif_lists_join, bif_lists_keydelete,
    bif_lists_keyfind, bif_lists_keysort, bif_lists_keystore, bif_lists_last, bif_lists_member,
    bif_lists_nth, bif_lists_reverse_2, bif_lists_seq, bif_lists_sort, bif_lists_unzip,
    bif_lists_zip,
};
use super::lists_hof_bifs::{bif_lists_filter, bif_lists_filtermap, bif_lists_foreach, bif_lists_map};
use super::maps_bifs::{
    bif_maps_filter, bif_maps_find, bif_maps_fold, bif_maps_keys, bif_maps_merge_with,
    bif_maps_put, bif_maps_to_list, bif_maps_update_with, bif_maps_values, bif_maps_with,
    bif_maps_without,
};
use super::json_bifs::{
    bif_json_decode, bif_json_encode, bif_json_encode_binary, bif_json_encode_float,
    bif_json_encode_integer,
};
use super::math_bifs::{bif_ceil, bif_exp, bif_floor, bif_log, bif_pow};
use super::string_bifs::{
    bif_equal as bif_string_equal, bif_find as bif_string_find,
    bif_is_empty as bif_string_is_empty, bif_length as bif_string_length,
    bif_lowercase as bif_string_lowercase, bif_next_grapheme as bif_string_next_grapheme,
    bif_pad as bif_string_pad, bif_replace as bif_string_replace4,
    bif_reverse as bif_string_reverse, bif_slice as bif_string_slice,
    bif_split as bif_string_split, bif_trim as bif_string_trim,
    bif_uppercase as bif_string_uppercase,
};
use super::type_conversion_bifs::{
    bif_binary_to_float, bif_binary_to_integer, bif_binary_to_integer_radix, bif_float,
    bif_integer_to_binary, bif_integer_to_binary_radix, bif_integer_to_list, bif_iolist_to_binary,
    bif_list_to_bitstring, bif_list_to_tuple, bif_tuple_to_list,
};
use super::uri_bifs::{
    bif_parse_query, bif_percent_decode, bif_percent_encode, bif_uri_parse,
    bif_uri_string_dissect_query, bif_uri_string_parse,
};

/// A stub BIF entry: (module_name, function_name, arity, capability, dirty_kind, implementation).
type StubBif = (
    &'static str,
    &'static str,
    u8,
    Capability,
    Option<DirtySchedulerKind>,
    NativeFn,
);

const STDLIB_STUBS: &[StubBif] = &[
    (
        "erlang",
        "binary_to_float",
        1,
        Capability::Pure,
        None,
        bif_binary_to_float,
    ),
    (
        "erlang",
        "binary_to_integer",
        1,
        Capability::Pure,
        None,
        bif_binary_to_integer,
    ),
    (
        "erlang",
        "binary_to_integer",
        2,
        Capability::Pure,
        None,
        bif_binary_to_integer_radix,
    ),
    ("erlang", "float", 1, Capability::Pure, None, bif_float),
    (
        "erlang",
        "integer_to_binary",
        1,
        Capability::Pure,
        None,
        bif_integer_to_binary,
    ),
    (
        "erlang",
        "integer_to_binary",
        2,
        Capability::Pure,
        None,
        bif_integer_to_binary_radix,
    ),
    (
        "erlang",
        "integer_to_list",
        1,
        Capability::Pure,
        None,
        bif_integer_to_list,
    ),
    (
        "erlang",
        "iolist_to_binary",
        1,
        Capability::Pure,
        None,
        bif_iolist_to_binary,
    ),
    (
        "erlang",
        "list_to_bitstring",
        1,
        Capability::Pure,
        None,
        bif_list_to_bitstring,
    ),
    (
        "erlang",
        "list_to_tuple",
        1,
        Capability::Pure,
        None,
        bif_list_to_tuple,
    ),
    (
        "erlang",
        "tuple_to_list",
        1,
        Capability::Pure,
        None,
        bif_tuple_to_list,
    ),
    ("erlang", "band", 2, Capability::Pure, None, bif_band),
    ("erlang", "bnot", 1, Capability::Pure, None, bif_bnot),
    ("erlang", "bor", 2, Capability::Pure, None, bif_bor),
    ("erlang", "bsl", 2, Capability::Pure, None, bif_bsl),
    ("erlang", "bsr", 2, Capability::Pure, None, bif_bsr),
    ("erlang", "bxor", 2, Capability::Pure, None, bif_bxor),
    ("math", "ceil", 1, Capability::Pure, None, bif_ceil),
    ("math", "floor", 1, Capability::Pure, None, bif_floor),
    ("math", "exp", 1, Capability::Pure, None, bif_exp),
    ("math", "log", 1, Capability::Pure, None, bif_log),
    ("math", "pow", 2, Capability::Pure, None, bif_pow),
    (
        "rand",
        "uniform",
        0,
        Capability::Entropy,
        None,
        bif_rand_uniform,
    ),
    (
        "logger",
        "warning",
        2,
        Capability::ExternalIo,
        None,
        bif_logger_warning,
    ),
    (
        "unicode",
        "characters_to_list",
        1,
        Capability::Pure,
        None,
        bif_characters_to_list,
    ),
    (
        "unicode",
        "characters_to_binary",
        1,
        Capability::Pure,
        None,
        bif_characters_to_binary,
    ),
    (
        "sys",
        "debug_options",
        1,
        Capability::Pure,
        None,
        bif_debug_options,
    ),
    (
        "gleam_stdlib",
        "identity",
        1,
        Capability::Pure,
        None,
        bif_identity,
    ),
    (
        "gleam_stdlib",
        "classify_dynamic",
        1,
        Capability::Pure,
        None,
        bif_classify_dynamic,
    ),
    ("gleam_stdlib", "dict", 1, Capability::Pure, None, bif_dict),
    (
        "gleam_stdlib",
        "float",
        1,
        Capability::Pure,
        None,
        bif_gleam_float,
    ),
    (
        "gleam_stdlib",
        "float_to_string",
        1,
        Capability::Pure,
        None,
        bif_float_to_string,
    ),
    (
        "gleam_stdlib",
        "index",
        2,
        Capability::Pure,
        None,
        bif_index,
    ),
    ("gleam_stdlib", "int", 1, Capability::Pure, None, bif_int),
    (
        "gleam_stdlib",
        "int_from_base_string",
        2,
        Capability::Pure,
        None,
        bif_int_from_base_string,
    ),
    (
        "gleam_stdlib",
        "parse_float",
        1,
        Capability::Pure,
        None,
        bif_parse_float,
    ),
    (
        "gleam_stdlib",
        "parse_int",
        1,
        Capability::Pure,
        None,
        bif_parse_int,
    ),
    (
        "gleam_stdlib",
        "is_null",
        1,
        Capability::Pure,
        None,
        bif_is_null,
    ),
    (
        "gleam_stdlib",
        "list",
        5,
        Capability::Pure,
        None,
        bif_gleam_list,
    ),
    (
        "gleam_stdlib",
        "map_get",
        2,
        Capability::Pure,
        None,
        bif_map_get,
    ),
    (
        "gleam_stdlib",
        "print",
        1,
        Capability::ExternalIo,
        None,
        bif_print,
    ),
    (
        "gleam_stdlib",
        "print_error",
        1,
        Capability::ExternalIo,
        None,
        bif_print_error,
    ),
    (
        "gleam_stdlib",
        "println",
        1,
        Capability::ExternalIo,
        None,
        bif_println,
    ),
    (
        "gleam_stdlib",
        "println_error",
        1,
        Capability::ExternalIo,
        None,
        bif_println_error,
    ),
    (
        "gleam_stdlib",
        "wrap_list",
        1,
        Capability::Pure,
        None,
        bif_wrap_list,
    ),
    (
        "gleam_stdlib",
        "parse_query",
        1,
        Capability::Pure,
        None,
        bif_parse_query,
    ),
    (
        "gleam_stdlib",
        "percent_decode",
        1,
        Capability::Pure,
        None,
        bif_percent_decode,
    ),
    (
        "gleam_stdlib",
        "percent_encode",
        1,
        Capability::Pure,
        None,
        bif_percent_encode,
    ),
    (
        "gleam_stdlib",
        "uri_parse",
        1,
        Capability::Pure,
        None,
        bif_uri_parse,
    ),
    (
        "gleam_stdlib",
        "base16_decode",
        1,
        Capability::Pure,
        None,
        bif_gleam_base16_decode,
    ),
    (
        "gleam_stdlib",
        "base16_encode",
        1,
        Capability::Pure,
        None,
        bif_gleam_base16_encode,
    ),
    (
        "gleam_stdlib",
        "base64_decode",
        1,
        Capability::Pure,
        None,
        bif_gleam_base64_decode,
    ),
    (
        "gleam_stdlib",
        "base64_encode",
        2,
        Capability::Pure,
        None,
        bif_gleam_base64_encode,
    ),
    (
        "gleam_stdlib",
        "bit_array",
        1,
        Capability::Pure,
        None,
        bif_gleam_bit_array,
    ),
    (
        "gleam_stdlib",
        "bit_array_concat",
        1,
        Capability::Pure,
        None,
        bif_gleam_bit_array_concat,
    ),
    (
        "gleam_stdlib",
        "bit_array_pad_to_bytes",
        1,
        Capability::Pure,
        None,
        bif_gleam_bit_array_pad_to_bytes,
    ),
    (
        "gleam_stdlib",
        "bit_array_slice",
        3,
        Capability::Pure,
        None,
        bif_gleam_bit_array_slice,
    ),
    (
        "gleam_stdlib",
        "bit_array_to_int_and_size",
        1,
        Capability::Pure,
        None,
        bif_gleam_bit_array_to_int_and_size,
    ),
    (
        "gleam_stdlib",
        "string_replace",
        3,
        Capability::Pure,
        None,
        bif_string_replace,
    ),
    (
        "gleam_stdlib",
        "less_than",
        2,
        Capability::Pure,
        None,
        bif_less_than,
    ),
    (
        "gleam_stdlib",
        "slice",
        3,
        Capability::Pure,
        None,
        bif_slice,
    ),
    (
        "gleam_stdlib",
        "crop_string",
        2,
        Capability::Pure,
        None,
        bif_crop_string,
    ),
    (
        "gleam_stdlib",
        "contains_string",
        2,
        Capability::Pure,
        None,
        bif_contains_string,
    ),
    (
        "gleam_stdlib",
        "string_starts_with",
        2,
        Capability::Pure,
        None,
        bif_string_starts_with,
    ),
    (
        "gleam_stdlib",
        "string_ends_with",
        2,
        Capability::Pure,
        None,
        bif_string_ends_with,
    ),
    (
        "gleam_stdlib",
        "string_pop_grapheme",
        1,
        Capability::Pure,
        None,
        bif_string_pop_grapheme,
    ),
    (
        "gleam_stdlib",
        "utf_codepoint_list_to_string",
        1,
        Capability::Pure,
        None,
        bif_utf_codepoint_list_to_string,
    ),
    (
        "gleam_stdlib",
        "inspect",
        1,
        Capability::Pure,
        None,
        bif_inspect,
    ),
    (
        "gleam_stdlib",
        "string_remove_prefix",
        2,
        Capability::Pure,
        None,
        bif_string_remove_prefix,
    ),
    (
        "gleam_stdlib",
        "string_remove_suffix",
        2,
        Capability::Pure,
        None,
        bif_string_remove_suffix,
    ),
    (
        "gleam_stdlib",
        "iodata_append",
        2,
        Capability::Pure,
        None,
        bif_iodata_append,
    ),
    (
        "uri_string",
        "parse",
        1,
        Capability::Pure,
        None,
        bif_uri_string_parse,
    ),
    (
        "uri_string",
        "dissect_query",
        1,
        Capability::Pure,
        None,
        bif_uri_string_dissect_query,
    ),
    (
        "string",
        "length",
        1,
        Capability::Pure,
        None,
        bif_string_length,
    ),
    (
        "string",
        "reverse",
        1,
        Capability::Pure,
        None,
        bif_string_reverse,
    ),
    (
        "string",
        "lowercase",
        1,
        Capability::Pure,
        None,
        bif_string_lowercase,
    ),
    (
        "string",
        "uppercase",
        1,
        Capability::Pure,
        None,
        bif_string_uppercase,
    ),
    ("string", "trim", 2, Capability::Pure, None, bif_string_trim),
    (
        "string",
        "split",
        3,
        Capability::Pure,
        None,
        bif_string_split,
    ),
    ("string", "find", 2, Capability::Pure, None, bif_string_find),
    (
        "string",
        "next_grapheme",
        1,
        Capability::Pure,
        None,
        bif_string_next_grapheme,
    ),
    ("string", "pad", 4, Capability::Pure, None, bif_string_pad),
    (
        "string",
        "replace",
        4,
        Capability::Pure,
        None,
        bif_string_replace4,
    ),
    (
        "string",
        "slice",
        3,
        Capability::Pure,
        None,
        bif_string_slice,
    ),
    (
        "string",
        "equal",
        2,
        Capability::Pure,
        None,
        bif_string_equal,
    ),
    (
        "string",
        "is_empty",
        1,
        Capability::Pure,
        None,
        bif_string_is_empty,
    ),
    ("binary", "part", 3, Capability::Pure, None, bif_binary_part),
    (
        "binary",
        "encode_hex",
        1,
        Capability::Pure,
        None,
        bif_binary_encode_hex,
    ),
    (
        "binary",
        "decode_hex",
        1,
        Capability::Pure,
        None,
        bif_binary_decode_hex,
    ),
    (
        "base64",
        "encode",
        2,
        Capability::Pure,
        None,
        bif_base64_encode,
    ),
    (
        "base64",
        "decode",
        1,
        Capability::Pure,
        None,
        bif_base64_decode,
    ),
    (
        "io",
        "put_chars",
        1,
        Capability::ExternalIo,
        None,
        bif_io_put_chars_1,
    ),
    (
        "io",
        "put_chars",
        2,
        Capability::ExternalIo,
        None,
        bif_io_put_chars_2,
    ),
    (
        "io",
        "format",
        2,
        Capability::ExternalIo,
        None,
        bif_io_format_2,
    ),
    (
        "io",
        "format",
        3,
        Capability::ExternalIo,
        None,
        bif_io_format_3,
    ),
    (
        "io",
        "get_line",
        1,
        Capability::ExternalIo,
        None,
        bif_io_get_line_1,
    ),
    (
        "io",
        "setopts",
        2,
        Capability::ExternalIo,
        None,
        bif_io_setopts_2,
    ),
    (
        "io_lib",
        "format",
        2,
        Capability::ExternalIo,
        None,
        bif_io_lib_format_2,
    ),
    (
        "init",
        "stop",
        1,
        Capability::ExternalIo,
        None,
        bif_init_stop,
    ),
    // Non-higher-order collection BIFs (B-028a):
    (
        "maps",
        "from_list",
        1,
        Capability::Pure,
        None,
        bif_maps_from_list,
    ),
    ("maps", "merge", 2, Capability::Pure, None, bif_maps_merge),
    ("maps", "remove", 2, Capability::Pure, None, bif_maps_remove),
    // maps:map/2 uses continuation trampolines for closure calls.
    ("maps", "map", 2, Capability::Pure, None, bif_maps_map),
    ("maps", "put", 3, Capability::Pure, None, bif_maps_put),
    ("maps", "find", 2, Capability::Pure, None, bif_maps_find),
    ("maps", "keys", 1, Capability::Pure, None, bif_maps_keys),
    ("maps", "values", 1, Capability::Pure, None, bif_maps_values),
    (
        "maps",
        "to_list",
        1,
        Capability::Pure,
        None,
        bif_maps_to_list,
    ),
    ("maps", "fold", 3, Capability::Pure, None, bif_maps_fold),
    ("maps", "filter", 2, Capability::Pure, None, bif_maps_filter),
    (
        "maps",
        "merge_with",
        3,
        Capability::Pure,
        None,
        bif_maps_merge_with,
    ),
    (
        "maps",
        "update_with",
        4,
        Capability::Pure,
        None,
        bif_maps_update_with,
    ),
    ("maps", "with", 2, Capability::Pure, None, bif_maps_with),
    (
        "maps",
        "without",
        2,
        Capability::Pure,
        None,
        bif_maps_without,
    ),
    (
        "lists",
        "reverse",
        1,
        Capability::Pure,
        None,
        bif_lists_reverse,
    ),
    (
        "lists",
        "append",
        1,
        Capability::Pure,
        None,
        bif_lists_append_1,
    ),
    (
        "lists",
        "append",
        2,
        Capability::Pure,
        None,
        bif_lists_append_2,
    ),
    ("lists", "join", 2, Capability::Pure, None, bif_lists_join),
    ("lists", "nth", 2, Capability::Pure, None, bif_lists_nth),
    (
        "lists",
        "member",
        2,
        Capability::Pure,
        None,
        bif_lists_member,
    ),
    (
        "lists",
        "keyfind",
        3,
        Capability::Pure,
        None,
        bif_lists_keyfind,
    ),
    ("lists", "last", 1, Capability::Pure, None, bif_lists_last),
    ("lists", "sort", 1, Capability::Pure, None, bif_lists_sort),
    (
        "lists",
        "flatten",
        1,
        Capability::Pure,
        None,
        bif_lists_flatten,
    ),
    ("lists", "zip", 2, Capability::Pure, None, bif_lists_zip),
    ("lists", "unzip", 1, Capability::Pure, None, bif_lists_unzip),
    (
        "lists",
        "filter",
        2,
        Capability::Pure,
        None,
        bif_lists_filter,
    ),
    (
        "lists",
        "filtermap",
        2,
        Capability::Pure,
        None,
        bif_lists_filtermap,
    ),
    ("lists", "map", 2, Capability::Pure, None, bif_lists_map),
    (
        "lists",
        "reverse",
        2,
        Capability::Pure,
        None,
        bif_lists_reverse_2,
    ),
    ("lists", "seq", 2, Capability::Pure, None, bif_lists_seq),
    (
        "lists",
        "keystore",
        4,
        Capability::Pure,
        None,
        bif_lists_keystore,
    ),
    (
        "lists",
        "keysort",
        2,
        Capability::Pure,
        None,
        bif_lists_keysort,
    ),
    (
        "lists",
        "keydelete",
        3,
        Capability::Pure,
        None,
        bif_lists_keydelete,
    ),
    (
        "lists",
        "foreach",
        2,
        Capability::Pure,
        None,
        bif_lists_foreach,
    ),
    (
        "timer",
        "sleep",
        1,
        Capability::Clock,
        Some(DirtySchedulerKind::Io),
        bif_timer_sleep,
    ),
    ("json", "decode", 1, Capability::Pure, None, bif_json_decode),
    ("json", "encode", 1, Capability::Pure, None, bif_json_encode),
    (
        "json",
        "encode_integer",
        1,
        Capability::Pure,
        None,
        bif_json_encode_integer,
    ),
    (
        "json",
        "encode_float",
        1,
        Capability::Pure,
        None,
        bif_json_encode_float,
    ),
    (
        "json",
        "encode_binary",
        1,
        Capability::Pure,
        None,
        bif_json_encode_binary,
    ),
    (
        "erlang",
        "fun_info",
        2,
        Capability::Pure,
        None,
        bif_fun_info,
    ),
    (
        "io_lib_format",
        "fwrite_g",
        1,
        Capability::Pure,
        None,
        bif_fwrite_g,
    ),
];

/// Registers all stdlib stub BIFs under their OTP module names.
pub fn register_stdlib_stubs(
    registry: &BifRegistryImpl,
    atom_table: &AtomTable,
) -> Result<(), NativeRegistrationError> {
    for &(module_name, function_name, arity, capability, dirty_kind, native_function) in
        STDLIB_STUBS
    {
        let module = atom_table.intern(module_name);
        let function = atom_table.intern(function_name);
        register_stub(
            registry,
            module,
            function,
            arity,
            native_function,
            capability,
            dirty_kind,
        )?;
    }

    Ok(())
}

fn register_stub(
    registry: &BifRegistryImpl,
    module: Atom,
    function: Atom,
    arity: u8,
    native_function: NativeFn,
    capability: Capability,
    dirty_kind: Option<DirtySchedulerKind>,
) -> Result<(), NativeRegistrationError> {
    if let Some(kind) = dirty_kind {
        registry.register_dirty(module, function, arity, native_function, kind, capability)
    } else {
        registry.register(module, function, arity, native_function, capability)
    }
}
